## **Imports**

In [0]:
from numpy.random import seed
import tensorflow
tensorflow.random.set_seed(404)


In [0]:
import os
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from datetime import datetime

from PIL import Image

## **Constants**

In [0]:
X_TRAIN_PATH = '/content/drive/My Drive/Machine Learning Neural Network/HandWriting Recognition/MNIST/digit_xtrain.csv'
X_TEST_PATH = '/content/drive/My Drive/Machine Learning Neural Network/HandWriting Recognition/MNIST/digit_xtest.csv'
Y_TRAIN_PATH = '/content/drive/My Drive/Machine Learning Neural Network/HandWriting Recognition/MNIST/digit_ytrain.csv'
Y_TEST_PATH = '/content/drive/My Drive/Machine Learning Neural Network/HandWriting Recognition/MNIST/digit_ytest.csv'


In [0]:
NR_CLASSES = 10
VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANEL = 1
TOTAL_NUM_INPUT = IMAGE_WIDTH * IMAGE_HEIGHT * CHANEL

LOGGING_PATH = '/content/drive/My Drive/Machine Learning Neural Network/HandWriting Recognition/tensorboard_mnist_digit_log/'

## **Gether Data**

In [455]:
%%time
y_train_all = np.loadtxt(Y_TRAIN_PATH, delimiter=',', dtype=int)

CPU times: user 220 ms, sys: 1.05 ms, total: 221 ms
Wall time: 231 ms


In [456]:
y_train_all.shape

(60000,)

In [457]:
%%time
y_test = np.loadtxt(Y_TEST_PATH, delimiter=',', dtype=int)

CPU times: user 35.4 ms, sys: 0 ns, total: 35.4 ms
Wall time: 37.7 ms


In [458]:
y_test.shape

(10000,)

In [459]:
%%time
x_train_all = np.loadtxt(X_TRAIN_PATH, delimiter=',', dtype=int)

CPU times: user 39.7 s, sys: 775 ms, total: 40.5 s
Wall time: 40.5 s


In [460]:
x_train_all.shape

(60000, 784)

In [461]:
%%time
x_test = np.loadtxt(X_TEST_PATH, delimiter=',', dtype=int)

CPU times: user 6.61 s, sys: 146 ms, total: 6.76 s
Wall time: 6.76 s


In [462]:
x_test.shape

(10000, 784)

image resoluation is 28 * 28 * 1, 1 is color chanel 784

## **Explore Data**

In [463]:
print(x_train_all)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## **Data Preprocessing**

In [0]:
x_train_all, x_test = x_train_all / 255.0, x_test/255.0

In [465]:
x_train_all

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [466]:
x_train_all.shape

(60000, 784)

In [467]:
y_train_all

array([5, 0, 4, ..., 5, 6, 8])

In [0]:
y_train_all = np.eye(NR_CLASSES)[y_train_all]


In [469]:
y_train_all

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [470]:
y_train_all.shape

(60000, 10)

In [0]:
y_test = np.eye(NR_CLASSES)[y_test]

In [472]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## **create validation dataset**

In [473]:
x_train_all.shape

(60000, 784)

In [0]:
x_val = x_train_all[:VALIDATION_SIZE]
y_val = y_train_all[:VALIDATION_SIZE]

In [475]:
y_val

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [0]:
x_train = x_train_all[VALIDATION_SIZE:]
y_train = y_train_all[VALIDATION_SIZE:]

In [477]:
x_train.shape

(50000, 784)

In [478]:
y_train.shape

(50000, 10)

In [479]:
x_val.shape

(10000, 784)

In [480]:
y_val.shape

(10000, 10)

## **Create Tensorflow Graph**

In [0]:
X = tf.placeholder(dtype=tf.float32, shape=[None, TOTAL_NUM_INPUT], name='X')
Y = tf.placeholder(dtype=tf.float32, shape=[None, NR_CLASSES], name='labels')

## **Neural Network Architecture**
hyperparamiter

In [0]:
nr_epochs = 50
# learninig_rate = 1e-4 #0.0001

learninig_rate = 1e-3

n_hidden1 = 512
n_hidden2 = 64


In [0]:
def setup_layer(input, weight_dims, bias_dims, name):
  # layer creating function

  with tf.name_scope(name): 
    # hrouping operation together. pretty of graph
    
    initial_weight = tf.truncated_normal(shape=weight_dims, stddev=0.1, seed=42)
    w = tf.Variable(initial_value=initial_weight, name='W')


    intial_bias = tf.constant(value=0.0, shape=bias_dims) 
    b = tf.Variable(initial_value=intial_bias, name='B')

    layer_in = tf.matmul(input, w) + b

    if name=='out':
      layer_out = tf.nn.softmax(layer_in)
    else:
      layer_out = tf.nn.relu(layer_in)
    tf.summary.histogram('weight', w)
    tf.summary.histogram('bias', b)

    return layer_out


In [0]:
layer_1 = setup_layer(input=X, weight_dims=[TOTAL_NUM_INPUT, n_hidden1],
                      bias_dims=[n_hidden1],name='layer_1')
# using drop layer 
layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='drop_out_layer')

layer_2 = setup_layer(input=layer_drop, weight_dims=[n_hidden1, n_hidden2],
                      bias_dims=[n_hidden2],name='layer_2')

output = setup_layer(input=layer_2, weight_dims=[n_hidden2, NR_CLASSES],
                      bias_dims=[NR_CLASSES],name='out')

model_name = f'{n_hidden1}-{n_hidden2} LR {learninig_rate} E {nr_epochs}'

#**Tensorbords Setup**

In [485]:
folder_name = f"{model_name} {datetime.now().strftime('%Y%b%d %H:%M')}"
print(folder_name)
directory = os.path.join(LOGGING_PATH, folder_name)
try:
  os.makedirs(directory)
except OSError as err:
  print(err.__str__)
else:
  print(f'folder created name is {folder_name}')

512-64 LR 0.001 E 50 2020Apr20 06:50
folder created name is 512-64 LR 0.001 E 50 2020Apr20 06:50


## **Loss Optimization & metrics**

Define Loss Fucntion

In [0]:
with tf.name_scope('loss'):
  loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))

##**Optimizer setup**



In [0]:
with tf.name_scope('optimizer'):
  optimizer = tf.train.AdamOptimizer(learninig_rate)
  train_step = optimizer.minimize(loss)

Accuracy of Metrics

In [0]:
with tf.name_scope('accuracy_calculation'):
  correct_prediction = tf.equal(tf.argmax(output, axis=1), tf.argmax(Y, axis=1))
  accuracy = tf.reduce_mean(tf.cast(correct_prediction, dtype=tf.float32))

In [0]:
with tf.name_scope('performance'):
  tf.summary.scalar('summary', accuracy)
  tf.summary.scalar('loss', loss)

#**Check input in tensorboard**

In [0]:
with tf.name_scope('show_image'):
  x_image = tf.reshape(X, [-1, 28,28,1])
  tf.summary.image('image_input', x_image, max_outputs=4)

##**Run Session**

In [0]:
sess = tf.Session()

##**Setup file writer for summary**


In [0]:
merged_summary = tf.summary.merge_all()
train_writer = tf.summary.FileWriter(directory + '/train')
train_writer.add_graph(sess.graph)

validation_writer = tf.summary.FileWriter(directory + '/validation')
# validation and training are using same graph

In [493]:
merged_summary

<tf.Tensor 'Merge/MergeSummary:0' shape=() dtype=string>

In [0]:
# initize all global variable
init = tf.global_variables_initializer()
sess.run(init)

In [0]:
# w3.eval(sess)

#**Batching (Split) Data**

In [0]:
size_batch = 1000

In [0]:
num_examples = y_train.shape[0]

In [0]:
nr_iterations = int(num_examples / size_batch)

In [0]:
index_epochs = 0 # using to track batch

In [0]:
def next_batch(batch_size, data, label):
  
  global index_epochs
  global num_examples

  start = index_epochs
  index_epochs += batch_size
  if index_epochs > num_examples:
    start = 0
    index_epochs = batch_size

  end = index_epochs

  return data[start:end], label[start:end]

##**Training loop**

In [501]:
for epoch in range(nr_epochs):
  # =============Training data set ==========================

  for i in range(nr_iterations):

    batch_x, batch_y = next_batch(batch_size=size_batch, data=x_train, label=y_train)
    feed_dictionary = {X: batch_x, Y:batch_y}
    sess.run(train_step, feed_dict=feed_dictionary)

  s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionary)
  train_writer.add_summary(s, epoch)

  print(f'Epochs {epoch} \t Training accuracy {batch_accuracy}')

  # =============validation data set ==========================
  summary = sess.run(fetches=merged_summary, feed_dict={X: x_val, Y: y_val})
  validation_writer.add_summary(summary, epoch)

print('training done')

Epochs 0 	 Training accuracy 0.8629999756813049
Epochs 1 	 Training accuracy 0.8809999823570251
Epochs 2 	 Training accuracy 0.9179999828338623
Epochs 3 	 Training accuracy 0.9620000123977661
Epochs 4 	 Training accuracy 0.9739999771118164
Epochs 5 	 Training accuracy 0.9760000109672546
Epochs 6 	 Training accuracy 0.9769999980926514
Epochs 7 	 Training accuracy 0.9789999723434448
Epochs 8 	 Training accuracy 0.9800000190734863
Epochs 9 	 Training accuracy 0.9800000190734863
Epochs 10 	 Training accuracy 0.9819999933242798
Epochs 11 	 Training accuracy 0.9850000143051147
Epochs 12 	 Training accuracy 0.9860000014305115
Epochs 13 	 Training accuracy 0.9850000143051147
Epochs 14 	 Training accuracy 0.9879999756813049
Epochs 15 	 Training accuracy 0.9890000224113464
Epochs 16 	 Training accuracy 0.9890000224113464
Epochs 17 	 Training accuracy 0.984000027179718
Epochs 18 	 Training accuracy 0.9909999966621399
Epochs 19 	 Training accuracy 0.9900000095367432
Epochs 20 	 Training accuracy 0

#**Make a Prediction**

In [502]:
img = Image.open('/content/drive/My Drive/Machine Learning Neural Network/HandWriting Recognition/MNIST/test_img.png')
img

In [503]:
# convert to grayscale. trained image are balck bacgground with whight digit
balck_whight = img.convert('L')
balck_whight



In [504]:
image_array = np.invert(balck_whight)
image_array.shape

(28, 28)

In [505]:
# convert to flantent array
test_img = image_array.ravel()
test_img.shape

(784,)

In [506]:
prediction = sess.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[test_img]})
print(f'prediction for test image is {prediction}')

prediction for test image is [2]


#**Testing And Evaluation**

In [508]:
test_accuracy = sess.run(fetches=accuracy, feed_dict={X:x_test, Y:y_test})
print(f'Accuracy of test set is {test_accuracy:0.2%}')

Accuracy of test set is 97.61%


#**Reset every thing for next run**

In [0]:
train_writer.close()
validation_writer.close()
sess.close()
tf.reset_default_graph()

#**layer creatin referance. first stage**

first hidden layer

In [0]:
# with tf.name_scope('first_hiden_layer'):

#   initial_weight1 = tf.truncated_normal(shape=[TOTAL_NUM_INPUT, n_hidden1], stddev=0.1, seed=42)
#   w1 = tf.Variable(initial_value=initial_weight1, name='w1')

#   intial_bias1 = tf.constant(value=0.0, shape=[n_hidden1]) 
#   b1 = tf.Variable(initial_value=intial_bias1, name='b1')

#   layer1_in = tf.matmul(X, w1) + b1

#   layer1_out = tf.nn.relu(features=layer1_in)

secound hidden layer

In [0]:
# with tf.name_scope('secound_hidden_layer'):
#   initial_weight2 = tf.truncated_normal(shape=[n_hidden1, n_hidden2], stddev=0.1, seed=42)
#   w2 = tf.Variable(initial_value=initial_weight2, name='w2')

#   intial_bias2 = tf.constant(value=0.0, shape=[n_hidden2]) 
#   b2 = tf.Variable(initial_value=intial_bias2, name='b2')

#   layer2_in = tf.matmul(layer1_out, w2) + b2

#   layer2_out = tf.nn.relu(features=layer2_in)

Third hidden layer

In [0]:
# with tf.name_scope('output_layer'): # hrouping operation together. pretty of graph
#   initial_weight3 = tf.truncated_normal(shape=[n_hidden2, NR_CLASSES], stddev=0.1, seed=42)
#   w3 = tf.Variable(initial_value=initial_weight3, name='w3')


#   intial_bias3 = tf.constant(value=0.0, shape=[NR_CLASSES]) 
#   b3 = tf.Variable(initial_value=intial_bias3, name='b3')

#   layer3_in = tf.matmul(layer2_out, w3) + b3
#   output = tf.nn.softmax(layer3_in)